[package]
name = "french_quiz_game"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.42"
serde = { version = "1.0.228", features = ["derive"] }
serde_yaml = "0.9"
rand = "0.10.0-rc.5"

